# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: app/test.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='app/test.proto',
  package='lmjwtest',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n\x0e\x61pp/test.proto\x12\x08lmjwtest\"N\n\tplaintext\x12\x17\n\x0fpttransactionID\x18\x01 \x01(\t\x12\x14\n\x0cptproperties\x18\x02 \x01(\t\x12\x12\n\nptsenderID\x18\x03 \x01(\t\"R\n\nencodetext\x12\x18\n\x10\x65nctransactionID\x18\x01 \x01(\t\x12\x15\n\rencproperties\x18\x02 \x01(\t\x12\x13\n\x0b\x65ncsenderID\x18\x03 \x01(\t2I\n\rEncodeService\x12\x38\n\tGetEncode\x12\x13.lmjwtest.plaintext\x1a\x14.lmjwtest.encodetext\"\x00\x62\x06proto3')
)




_PLAINTEXT = _descriptor.Descriptor(
  name='plaintext',
  full_name='lmjwtest.plaintext',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='pttransactionID', full_name='lmjwtest.plaintext.pttransactionID', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='ptproperties', full_name='lmjwtest.plaintext.ptproperties', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='ptsenderID', full_name='lmjwtest.plaintext.ptsenderID', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=28,
  serialized_end=106,
)


_ENCODETEXT = _descriptor.Descriptor(
  name='encodetext',
  full_name='lmjwtest.encodetext',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='enctransactionID', full_name='lmjwtest.encodetext.enctransactionID', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='encproperties', full_name='lmjwtest.encodetext.encproperties', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='encsenderID', full_name='lmjwtest.encodetext.encsenderID', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=108,
  serialized_end=190,
)

DESCRIPTOR.message_types_by_name['plaintext'] = _PLAINTEXT
DESCRIPTOR.message_types_by_name['encodetext'] = _ENCODETEXT
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

plaintext = _reflection.GeneratedProtocolMessageType('plaintext', (_message.Message,), dict(
  DESCRIPTOR = _PLAINTEXT,
  __module__ = 'app.test_pb2'
  # @@protoc_insertion_point(class_scope:lmjwtest.plaintext)
  ))
_sym_db.RegisterMessage(plaintext)

encodetext = _reflection.GeneratedProtocolMessageType('encodetext', (_message.Message,), dict(
  DESCRIPTOR = _ENCODETEXT,
  __module__ = 'app.test_pb2'
  # @@protoc_insertion_point(class_scope:lmjwtest.encodetext)
  ))
_sym_db.RegisterMessage(encodetext)



_ENCODESERVICE = _descriptor.ServiceDescriptor(
  name='EncodeService',
  full_name='lmjwtest.EncodeService',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  serialized_start=192,
  serialized_end=265,
  methods=[
  _descriptor.MethodDescriptor(
    name='GetEncode',
    full_name='lmjwtest.EncodeService.GetEncode',
    index=0,
    containing_service=None,
    input_type=_PLAINTEXT,
    output_type=_ENCODETEXT,
    serialized_options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_ENCODESERVICE)

DESCRIPTOR.services_by_name['EncodeService'] = _ENCODESERVICE

# @@protoc_insertion_point(module_scope)
